name: Gregory Hubbard, Computer Engineer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
